project: 
  type: default
  output-dir: reports
  
revealjs:
     theme: default
     embed-resources: true
     width: 1280
     height: 720
     slide-number: true
     math: mathjax
     css: styles-reveal.css
     execute:
       eval: true
       echo: false
       warning: false
       message: false
     fig-width: 8
     fig-align: center
     progress: true
     transition: fade
     fig-responsive: true

bibliography: references.bib
cls: harvard-cite-them-right-11th-edition.csl